export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_GET_REQUEST = "USER_UPDATE_REQUEST";
export const USER_GET_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_GET_FAIL = "USER_UPDATE_FAIL";

export const USER_ALL_REQUEST = "USER_UPDATE_REQUEST";
export const USER_ALL_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_ALL_FAIL = "USER_UPDATE_FAIL";

export const USER_GETUSERBYSEARCH_REQUEST = "USER_GETUSERBYSEARCH_REQUEST";
export const USER_GETUSERBYSEARCH_SUCCESS = "USER_GETUSERBYSEARCH_SUCCESS";
export const USER_GETUSERBYSEARCH_FAIL = "USER_GETUSERBYSEARCH_FAIL";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_GET_DETAILS_REQUEST = "USER_GET_DETAILS_REQUEST";
export const USER_GET_DETAILS_SUCCESS = "USER_GET_DETAILS_SUCCESS";
export const USER_GET_DETAILS_FAIL = "USER_GET_DETAILS_FAIL";

export const USER_CONFIRM_REQUEST = "USER_CONFIRM_REQUEST";
export const USER_CONFIRM_SUCCESS = "USER_GET_DETAILS_SUCCESS";
export const USER_CONFIRM_FAIL = "USER_CONFIRM_FAIL";

export const EDIT_USER_FROM_ADMIN_FAIL = "EDIT_USER_FROM_ADMIN_FAIL";
export const EDIT_USER_FROM_ADMIN_REQUEST = "EDIT_USER_FROM_ADMIN_REQUEST";
export const EDIT_USER_FROM_ADMIN_SUCCESS = "EDIT_USER_FROM_ADMIN_SUCCESS";

